### ISSUE TITLE
Problem clicking on collections

### ISSUE THREAD

**Issue by cjmyers** [ICO2S/synbiohub#11]
Clicking on Collection, gives:

Error: collection not found at /usr/home/synbiohub/synbiohub/lib/get-sbol.js:81:25 at /usr/home/synbiohub/synbiohub/node_modules/async/lib/async.js:154:25 at /usr/home/synbiohub/synbiohub/lib/get-sbol.js:74:17 at /usr/home/synbiohub/synbiohub/node_modules/sbolstack-frontend/lib/store.js:109:13 at Request._callback (/usr/home/synbiohub/synbiohub/node_modules/sbolstack-frontend/lib/getSBOL.js:24:13) at Request.self.callback (/usr/home/synbiohub/synbiohub/node_modules/request/request.js:200:22) at emitTwo (events.js:87:13) at Request.emit (events.js:172:7) at Request.(/usr/home/synbiohub/synbiohub/node_modules/request/request.js:1067:10) at emitOne (events.js:82:20) at Request.emit (events.js:169:7) at IncomingMessage.(/usr/home/synbiohub/synbiohub/node_modules/request/request.js:988:12) at emitNone (events.js:72:20) at IncomingMessage.emit (events.js:166:7) at endReadableNT (_stream_readable.js:893:12) at doNTCallback2 (node.js:429:9) at process._tickCallback (node.js:343:17)

**Comment by cjmyers** [comment]
Seems to work now.
