### ISSUE TITLE
Problem with FetchNonLocalSBOL in getSBOL.js

### ISSUE THREAD

**Issue by cjmyers** [ICO2S/synbiohub#148]
This method throws this exception when the get returns invalid SBOL:

/Users/myers/git/synbiohub/node_modules/async/lib/async.js:30
            if (called) throw new Error("Callback was already called.");
                        ^

Error: Callback was already called.
    at /Users/myers/git/synbiohub/node_modules/async/lib/async.js:30:31
    at /Users/myers/git/synbiohub/node_modules/sboljs/lib/load/rdf/loadRDF.js:68:9
    at /Users/myers/git/synbiohub/node_modules/rdf-parser-abstract/index.js:26:13
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

This happens for example when the response is HTML.  This currently happens when the part cannot be fetched, since an HTML error page is sent back.  While changing this to respond with an error instead perhaps by using a different end point will solve this particular problem, it will not help when the page being dereferenced for some reason does return html.  So, it would be good to figure out how to fix this error.

**Comment by cjmyers** [comment]
Checked in hack to see if HTML served back, but still should fix the root of the problem which is loadRDF does not seem to fail correctly when it is not given an SBOL file.

**Comment by cjmyers** [comment]
Should be less of a problem if we use separate endpoint.  Also should only be called if it is in the web of registries.

**Comment by cjmyers** [comment]
Added a new endpoint, also only fetch when found in registry in the webOfRegistries.
