### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by cjmyers** [ICO2S/synbiohub#15]
When I try search, I get this error message:

ReferenceError: opts is not defined
  at Function.lucene (/usr/home/synbiohub/synbiohub/lib/search.js:102:13)
  at module.exports.stack.getPrefixes (/usr/home/synbiohub/synbiohub/lib/views/search.js:20:20)
  at Layer.handle [as handle_request] (/usr/home/synbiohub/synbiohub/node_modules/express/lib/router/layer.js:95:5)
  at next (/usr/home/synbiohub/synbiohub/node_modules/express/lib/router/route.js:131:13)
  at Route.dispatch (/usr/home/synbiohub/synbiohub/node_modules/express/lib/router/route.js:112:3)
  at Layer.handle [as handle_request] (/usr/home/synbiohub/synbiohub/node_modules/express/lib/router/layer.js:95:5)
  at /usr/home/synbiohub/synbiohub/node_modules/express/lib/router/index.js:277:22
  at param (/usr/home/synbiohub/synbiohub/node_modules/express/lib/router/index.js:349:14)
  at param (/usr/home/synbiohub/synbiohub/node_modules/express/lib/router/index.js:365:14)
  at Function.process_params (/usr/home/synbiohub/synbiohub/node_modules/express/lib/router/index.js:410:3)
  at next (/usr/home/synbiohub/synbiohub/node_modules/express/lib/router/index.js:271:10)
  at /usr/home/synbiohub/synbiohub/lib/app.js:99:13
  at Layer.handle [as handle_request] (/usr/home/synbiohub/synbiohub/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/usr/home/synbiohub/synbiohub/node_modules/express/lib/router/index.js:312:13)
  at /usr/home/synbiohub/synbiohub/node_modules/express/lib/router/index.js:280:7
  at Function.process_params (/usr/home/synbiohub/synbiohub/node_modules/express/lib/router/index.js:330:12)
  at next (/usr/home/synbiohub/synbiohub/node_modules/express/lib/router/index.js:271:10)
  at /usr/home/synbiohub/synbiohub/lib/app.js:76:13
  at Layer.handle [as handle_request] (/usr/home/synbiohub/synbiohub/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/usr/home/synbiohub/synbiohub/node_modules/express/lib/router/index.js:312:13)
  at /usr/home/synbiohub/synbiohub/node_modules/express/lib/router/index.js:280:7
  at Function.process_params (/usr/home/synbiohub/synbiohub/node_modules/express/lib/router/index.js:330:12)

**Comment by cjmyers** [comment]
I think I fixed front page search, but the component view page search is still broken.

**Comment by cjmyers** [comment]
Note search is only doing displayId, name, description for ComponentDefinitions.  Should enable search of, at a minimum, these fields for all TopLevel objects.

**Comment by cjmyers** [comment]
Fixed on component view page, but the hack is not too pretty.  I added new entries in app.js to account for the /search after the page URI for a component.  Cleaner would be to create the proper URI, but I'm not sure how to do that.  I don't want to hard code in the address of the stack.

**Comment by cjmyers** [comment]
Search list is also missing a Next button to see beyond the first 50 entries.

**Comment by cjmyers** [comment]
Closing
